# Generated by Django 4.1 on 2023-01-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_red', models.IntegerField(default=255)),
                ('time_green', models.IntegerField(default=255)),
                ('time_blue', models.IntegerField(default=255)),
                ('time_font', models.CharField(default='Montserrat-Black', max_length=255)),
                ('time_size', models.IntegerField(default=16)),
                ('time_format', models.IntegerField(choices=[(0, '%H:%M:%S'), (1, '%H:%M'), (2, '%I:%M:%S %p'), (3, '%I:%M %p')], default=0)),
                ('date_red', models.IntegerField(default=255)),
                ('date_green', models.IntegerField(default=255)),
                ('date_blue', models.IntegerField(default=255)),
                ('date_font', models.CharField(default='Montserrat-Medium', max_length=255)),
                ('date_size', models.IntegerField(default=12)),
                ('day_format', models.IntegerField(choices=[(0, '%A'), (1, '%a')], default=0)),
                ('date_format', models.IntegerField(choices=[(0, '%d/%m/%Y'), (1, '%d/%m/%y')], default=0)),
            ],
        ),
    ]
