# Generated by Django 4.1 on 2023-01-27 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenmodel',
            name='background_blue',
            field=models.IntegerField(default=255),
        ),
        migrations.AddField(
            model_name='screenmodel',
            name='background_green',
            field=models.IntegerField(default=255),
        ),
        migrations.AddField(
            model_name='screenmodel',
            name='background_red',
            field=models.IntegerField(default=255),
        ),
    ]
