# Generated by Django 4.1 on 2023-01-27 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0002_screenmodel_background_blue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenmodel',
            name='day_format',
            field=models.IntegerField(choices=[(0, '%A'), (1, '%a'), (2, '')], default=0),
        ),
    ]
